export const curatedYouTubePlaylists = [
  {
    id: 'PLvVVl_5u6dyzuU_ytBxGqIUSCmxh_WUzE',
    title: 'Nuestra Costa Ancestral',
    description:
      'Una selección audiovisual para recorrer la memoria, los hitos y los momentos principales de esta serie.',
    thumbnail: 'https://i.ytimg.com/vi/YNt3jN-fd3A/hqdefault.jpg',
    publishedAt: '28 dic 2025',
    videoCount: 1,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dyzuU_ytBxGqIUSCmxh_WUzE',
    videos: [
      {
        id: 'YNt3jN-fd3A',
        title: 'Nuestra Costa Ancestral | Ep. 01 Ramal Lompuya',
        thumbnail: 'https://i.ytimg.com/vi/YNt3jN-fd3A/hqdefault.jpg',
        publishedAt: '28 dic 2025',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dyzZwdjN_a_AyQakAksAd0Cx',
    title: 'Taller de Cine',
    description: 'Trabajos realizados por el taller de cine de nuestro arbolito.',
    thumbnail: 'https://i.ytimg.com/vi/5umNIkqvD6M/hqdefault.jpg',
    publishedAt: '06 ago 2025',
    videoCount: 1,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dyzZwdjN_a_AyQakAksAd0Cx',
    videos: [
      {
        id: '5umNIkqvD6M',
        title: 'OLVIDARTE - Marcelo Pavés (Videoclip Oficial)',
        thumbnail: 'https://i.ytimg.com/vi/5umNIkqvD6M/hqdefault.jpg',
        publishedAt: '06 ago 2025',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dyxqEU3f3yR9FfWn6Kt-c1bM',
    title: 'Entre Calles y Recuerdos',
    description:
      'Entre Calles y Recuerdos, un podcast de reconstrucción histórica que nos lleva al corazón de dos poblaciones de Coelemu.',
    thumbnail: 'https://i.ytimg.com/vi/26Re4iYLqfA/hqdefault.jpg',
    publishedAt: '28 abr 2025',
    videoCount: 2,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dyxqEU3f3yR9FfWn6Kt-c1bM',
    videos: [
      {
        id: '26Re4iYLqfA',
        title: 'Entre Calles y Recuerdos | Episodio 02 - Población 11 de Septiembre',
        thumbnail: 'https://i.ytimg.com/vi/26Re4iYLqfA/hqdefault.jpg',
        publishedAt: '28 abr 2025',
      },
      {
        id: 'Vh42WCgr6fM',
        title: 'Entre Calles y Recuerdos | Episodio 01 - Población Villa Madera',
        thumbnail: 'https://i.ytimg.com/vi/Vh42WCgr6fM/hqdefault.jpg',
        publishedAt: '31 mar 2025',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dyxZN_wuM1QDYFEG3ZA6pXax',
    title: 'Consejo Charlativo',
    description: 'Un podcast del Consejo Consultivo Adolescente del Hospital de Coelemu.',
    thumbnail: 'https://i.ytimg.com/vi/Lft5wc7kckw/hqdefault.jpg',
    publishedAt: '08 nov 2024',
    videoCount: 8,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dyxZN_wuM1QDYFEG3ZA6pXax',
    videos: [
      {
        id: 'Lft5wc7kckw',
        title: 'Consejo Charlativo | Tips para el bienestar',
        thumbnail: 'https://i.ytimg.com/vi/Lft5wc7kckw/hqdefault.jpg',
        publishedAt: '08 nov 2024',
      },
      {
        id: 'AogmHTjBvqI',
        title: 'Consejo Charlativo | Violencia en el pololeo',
        thumbnail: 'https://i.ytimg.com/vi/AogmHTjBvqI/hqdefault.jpg',
        publishedAt: '04 nov 2024',
      },
      {
        id: 'NYW1EzXemQc',
        title: 'Consejo Charlativo | Comunicación Efectiva',
        thumbnail: 'https://i.ytimg.com/vi/NYW1EzXemQc/hqdefault.jpg',
        publishedAt: '01 nov 2024',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dywiF2pXQOP1GbxFO9Bzil24',
    title: 'Reportajes Patrimoniales',
    description: 'Una colección disponible para seguir viendo esta serie en Arte y Vida TV.',
    thumbnail: 'https://i.ytimg.com/vi/ryBAteLZh18/hqdefault.jpg',
    publishedAt: '28 may 2024',
    videoCount: 1,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dywiF2pXQOP1GbxFO9Bzil24',
    videos: [
      {
        id: 'ryBAteLZh18',
        title: 'Reportaje Ptrimonial | La Historia del Dr. Contreras',
        thumbnail: 'https://i.ytimg.com/vi/ryBAteLZh18/hqdefault.jpg',
        publishedAt: '28 may 2024',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dywRrDB7g9_G-VrLjslqlLOg',
    title: 'Documentales La Cultura Vive en Tu Barrio',
    description: 'Compilación de documentales producidos para el proyecto.',
    thumbnail: 'https://i.ytimg.com/vi/EVY7mtJMDQ8/hqdefault.jpg',
    publishedAt: '22 abr 2024',
    videoCount: 18,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dywRrDB7g9_G-VrLjslqlLOg',
    videos: [
      {
        id: 'EVY7mtJMDQ8',
        title: 'La Cultura Vive en tu Barrio | Domingo Ortíz de Rozas - Coelemu',
        thumbnail: 'https://i.ytimg.com/vi/EVY7mtJMDQ8/hqdefault.jpg',
        publishedAt: '22 abr 2024',
      },
      {
        id: 'J-1HG0q1uhw',
        title: 'La Cultura Vive en Tu Barrio | Altos de Quirihue - Quirihue',
        thumbnail: 'https://i.ytimg.com/vi/J-1HG0q1uhw/hqdefault.jpg',
        publishedAt: '22 abr 2024',
      },
      {
        id: '11Qz4Iung8M',
        title: 'La Cultura Vive en Tu Barrio | Villa Valle Verde - Quillón',
        thumbnail: 'https://i.ytimg.com/vi/11Qz4Iung8M/hqdefault.jpg',
        publishedAt: '22 abr 2024',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dyxrzuGbjCwi1Qye0vQaT0SF',
    title: 'Arte y Vida en la Región de Aysén',
    description: 'Una colección disponible para seguir viendo esta serie en Arte y Vida TV.',
    thumbnail: 'https://i.ytimg.com/vi/6zSHT2WiDb8/hqdefault.jpg',
    publishedAt: '18 may 2023',
    videoCount: 2,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dyxrzuGbjCwi1Qye0vQaT0SF',
    videos: [
      {
        id: '6zSHT2WiDb8',
        title: 'Arte y Vida en la Región de Aysén | Chile Chico',
        thumbnail: 'https://i.ytimg.com/vi/6zSHT2WiDb8/hqdefault.jpg',
        publishedAt: '18 may 2023',
      },
      {
        id: 'LNcdMlp0_SQ',
        title: 'Arte y Vida en la Región de Aysén | Villa Mañihuales',
        thumbnail: 'https://i.ytimg.com/vi/LNcdMlp0_SQ/hqdefault.jpg',
        publishedAt: '01 jun 2023',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dyx4pFlesQOfLrAy_loQje0X',
    title: 'Trascendiendo a Cultores y Artistas de Itata',
    description: 'Una colección disponible para seguir viendo esta serie en Arte y Vida TV.',
    thumbnail: 'https://i.ytimg.com/vi/9PzRPaI8njk/hqdefault.jpg',
    publishedAt: '27 abr 2023',
    videoCount: 1,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dyx4pFlesQOfLrAy_loQje0X',
    videos: [
      {
        id: '9PzRPaI8njk',
        title: 'Resumen Trascendiendo a Cultores y Artistas de Itata',
        thumbnail: 'https://i.ytimg.com/vi/9PzRPaI8njk/hqdefault.jpg',
        publishedAt: '27 abr 2023',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dyzoH5tA_8plW8o3vbztKTc3',
    title: 'Ñuble: del paisaje a los colores',
    description: 'Una colección disponible para seguir viendo esta serie en Arte y Vida TV.',
    thumbnail: 'https://i.ytimg.com/vi/8i2HbDDSZ3w/hqdefault.jpg',
    publishedAt: '09 mar 2023',
    videoCount: 4,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dyzoH5tA_8plW8o3vbztKTc3',
    videos: [
      {
        id: '8i2HbDDSZ3w',
        title: 'ÑUBLE: Del paisaje a los colores | Chillán Viejo',
        thumbnail: 'https://i.ytimg.com/vi/8i2HbDDSZ3w/hqdefault.jpg',
        publishedAt: '09 mar 2023',
      },
      {
        id: 'j0va5mI7nEY',
        title: 'ÑUBLE: Del paisaje a los colores | San Fabián',
        thumbnail: 'https://i.ytimg.com/vi/j0va5mI7nEY/hqdefault.jpg',
        publishedAt: '09 mar 2023',
      },
      {
        id: 'c2uECCnLYhU',
        title: 'ÑUBLE: Del paisaje a los colores | El Carmen',
        thumbnail: 'https://i.ytimg.com/vi/c2uECCnLYhU/hqdefault.jpg',
        publishedAt: '09 mar 2023',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dyzzwQCpTJNsoBdTKsaAxmNT',
    title: 'ED2M',
    description: 'Una colección disponible para seguir viendo esta serie en Arte y Vida TV.',
    thumbnail: 'https://i.ytimg.com/vi/yugQgPG--r0/hqdefault.jpg',
    publishedAt: '25 feb 2023',
    videoCount: 3,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dyzzwQCpTJNsoBdTKsaAxmNT',
    videos: [
      {
        id: 'yugQgPG--r0',
        title: 'ENCUENTRO DE DOS MUNDOS 01 | Juan del Valle & Keko.EMC',
        thumbnail: 'https://i.ytimg.com/vi/yugQgPG--r0/hqdefault.jpg',
        publishedAt: '25 feb 2023',
      },
      {
        id: '9oga_e2qj8g',
        title: 'ENCUENTRO DE DOS MUNDOS 02 | Jocelyn Muñoz & El Irra',
        thumbnail: 'https://i.ytimg.com/vi/9oga_e2qj8g/hqdefault.jpg',
        publishedAt: '04 mar 2023',
      },
      {
        id: 'r1Fe06t6LC8',
        title: 'ENCUENTRO DE DOS MUNDOS 03 | Fernando Yáñez & West',
        thumbnail: 'https://i.ytimg.com/vi/r1Fe06t6LC8/hqdefault.jpg',
        publishedAt: '11 mar 2023',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dyxsTuLbpu1PJXZc_RpMlbCg',
    title: 'Cortometrajes documentales',
    description: 'Una colección disponible para seguir viendo esta serie en Arte y Vida TV.',
    thumbnail: 'https://i.ytimg.com/vi/wfu0_Tq981o/hqdefault.jpg',
    publishedAt: '30 nov 2022',
    videoCount: 11,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dyxsTuLbpu1PJXZc_RpMlbCg',
    videos: [
      {
        id: 'wfu0_Tq981o',
        title: 'La Revolución Pingüina en Coelemu',
        thumbnail: 'https://i.ytimg.com/vi/wfu0_Tq981o/hqdefault.jpg',
        publishedAt: '30 nov 2022',
      },
      {
        id: 'JK1Ls2VFcg0',
        title: 'La Once: breve historia de un barrio entre cerros coelemanos',
        thumbnail: 'https://i.ytimg.com/vi/JK1Ls2VFcg0/hqdefault.jpg',
        publishedAt: '30 jun 2023',
      },
      {
        id: 'BY_U2W_ed1A',
        title: 'Documental | Proyecto FICC',
        thumbnail: 'https://i.ytimg.com/vi/BY_U2W_ed1A/hqdefault.jpg',
        publishedAt: '31 ago 2023',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dyxVleJqo9I3mpG5SzrPBMrJ',
    title: 'Hablemos de Arte y Cultura',
    description: 'Una colección disponible para seguir viendo esta serie en Arte y Vida TV.',
    thumbnail: 'https://i.ytimg.com/vi/PpA0r5I3IIQ/hqdefault.jpg',
    publishedAt: '02 oct 2022',
    videoCount: 38,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dyxVleJqo9I3mpG5SzrPBMrJ',
    videos: [
      {
        id: 'PpA0r5I3IIQ',
        title: 'Hablemos de Arte y Cultura - Invitado Ernesto Bruno',
        thumbnail: 'https://i.ytimg.com/vi/PpA0r5I3IIQ/hqdefault.jpg',
        publishedAt: '02 oct 2022',
      },
      {
        id: 'L0axMCJpok8',
        title: 'Hablemos de Arte y Cultura - Resumen de Septiembre',
        thumbnail: 'https://i.ytimg.com/vi/L0axMCJpok8/hqdefault.jpg',
        publishedAt: '09 oct 2022',
      },
      {
        id: 'KyIuK5QhndM',
        title: 'Hablemos de Arte y Cultura - Invitado Gabriel Asanie',
        thumbnail: 'https://i.ytimg.com/vi/KyIuK5QhndM/hqdefault.jpg',
        publishedAt: '31 oct 2022',
      },
    ],
  },
  {
    id: 'PLvVVl_5u6dyyIgivW1Is7xTKe1t-q2Uwg',
    title: 'Arte y Vida',
    description: 'Una colección disponible para seguir viendo esta serie en Arte y Vida TV.',
    thumbnail: 'https://i.ytimg.com/vi/cg4jEZ-tQPU/hqdefault.jpg',
    publishedAt: '19 jun 2020',
    videoCount: 8,
    playlistUrl: 'https://www.youtube.com/playlist?list=PLvVVl_5u6dyyIgivW1Is7xTKe1t-q2Uwg',
    videos: [
      {
        id: 'cg4jEZ-tQPU',
        title: 'Javier Gasc/Hablemos de Música',
        thumbnail: 'https://i.ytimg.com/vi/cg4jEZ-tQPU/hqdefault.jpg',
        publishedAt: '19 jun 2020',
      },
      {
        id: 'ECkjwlddsBM',
        title: 'Cecilia Carrasco/Hablemos de Música',
        thumbnail: 'https://i.ytimg.com/vi/ECkjwlddsBM/hqdefault.jpg',
        publishedAt: '19 jun 2020',
      },
      {
        id: 'B1VOFNF56XE',
        title: 'SEREMI de las Culturas de Ñuble, visita la Casa-Taller de la Corporación Arte y Vida.',
        thumbnail: 'https://i.ytimg.com/vi/B1VOFNF56XE/hqdefault.jpg',
        publishedAt: '19 jun 2020',
      },
    ],
  },
] as const;
